# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "Use Case Template"
author: eScience Institute, University of Washington
logo: img/GeoSMART_logo.svg
only_build_toc_files: true

# Information about where the book exists on the web
repository:
  url: https://github.com/geo-smart/simple-template # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: 'force'

html:
  use_edit_page_button: true
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar: false

# Configure your Binder links, such as the URL of the BinderHub.
launch_buttons:
  notebook_interface: jupyterlab
  binderhub_url: "https://mybinder.org"

sphinx:
  config:
    # Required for PlotLy plots?
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
